# -*- coding: utf-8 -*-
"""waterquality.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YsH-_1jg5Ad5yH1e-Ph82nlxtrrYUgSv
"""

# Commented out IPython magic to ensure Python compatibility.
import os
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")
from lightgbm import LGBMClassifier
from sklearn.metrics import classification_report, confusion_matrix, roc_curve, roc_auc_score
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.preprocessing import StandardScaler
from imblearn.under_sampling import NearMiss
from sklearn.metrics import roc_auc_score, roc_curve, auc
import joblib


# %matplotlib inline

df=pd.read_csv("/content/waterQuality1.csv")
df.head()

df.shape

df.info()

missing_value = ['#NUM!', np.nan]
df=pd.read_csv("/content/waterQuality1.csv", na_values = missing_value)
df.isnull().sum()
#df['ammonia']=df['ammonia'].fillna(df.groupby(['is_safe'])['ammonia'].transform('mean'))
#df.isna().sum()

df.dropna( subset=['ammonia', 'is_safe'], axis=0, inplace=True)

df.isnull().sum()

df.duplicated().sum()

df.describe()

df.corr()

df['is_safe'].value_counts()

sns.countplot(df['is_safe'])
plt.show()

sns.countplot(df['arsenic'])
plt.show()

#box plot
fig, ax = plt.subplots(ncols=7, nrows=3, figsize=(20,10))
count = 0
ax = ax.flatten()
for i, value in df.items():
     sns.boxplot(y = i, data=df, ax=ax[count])
     count += 1
plt.tight_layout(pad=0.5, w_pad=0.7, h_pad=5.0)

#distribution of the data
df.hist(figsize=(14, 14))
plt.show()

#coorelation matrix

plt.figure(figsize=(18, 9))
sns.heatmap(df.corr(), annot=True, cmap='terrain')
plt.show()

import pandas as pd
from sklearn.multioutput import MultiOutputRegressor
from sklearn.ensemble import RandomForestRegressor


# Calculate the correlation with the output variable (e.g., 'is_safe')
correlations = df.corr()['is_safe']

# Sort the correlations in descending order and exclude the 'is_safe' column itself
sorted_correlations = correlations.drop('is_safe').abs().sort_values(ascending=False)

# Select the top three features with the highest correlation
top_features = sorted_correlations.index[:3]
top_features

# Use these three columns as the new target variables
targets = df[top_features]

# Use the remaining columns as features
features = df.drop(columns=['is_safe', *top_features])

from sklearn.multioutput import MultiOutputRegressor
from sklearn.model_selection import train_test_split
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.metrics import mean_squared_error, accuracy_score

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(features, targets, test_size=0.2, random_state=42)

# Train a multi-output regression model using GradientBoostingRegressor
regressor = MultiOutputRegressor(GradientBoostingRegressor(n_estimators=100, random_state=42))
regressor.fit(X_train, y_train)

# Make predictions using the trained model
predicted_targets = regressor.predict(X_test)

# Calculate Mean Squared Error (MSE) for each target variable
mse_values = [mean_squared_error(y_test[target], predicted_targets[:, i]) for i, target in enumerate(top_features)]

# Calculate Accuracy for each target variable (you need to define a threshold for classification)
threshold = 0.5  # You can adjust the threshold as needed
accuracy_values = [accuracy_score(y_test[target] > threshold, predicted_targets[:, i] > threshold) for i, target in enumerate(top_features)]

for i, target in enumerate(top_features):
    print(f"Target: {target}")
    print(f"MSE: {mse_values[i]:.2f}")
    print(f"Accuracy: {accuracy_values[i]:.2f}")

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.multioutput import MultiOutputRegressor
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import accuracy_score



# Select the target features
target_features = ['aluminium', 'cadmium']

# Use these two columns as the new target variables
targets = df[target_features]

# Use the remaining columns as features
features = df.drop(columns=target_features)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(features, targets, test_size=0.2, random_state=42)

# Train a multi-output regression model using GradientBoostingRegressor
regressor = MultiOutputRegressor(GradientBoostingRegressor(n_estimators=100, random_state=42))
regressor.fit(X_train, y_train)

# Make predictions using the trained model
predicted_targets = regressor.predict(X_test)

# Calculate Mean Squared Error (MSE) and R-squared for each target variable
mse_values = [mean_squared_error(y_test[target], predicted_targets[:, i]) for i, target in enumerate(target_features)]
r2_values = [r2_score(y_test[target], predicted_targets[:, i]) for i, target in enumerate(target_features)]

# Print MSE and R-squared for each target
for i, target in enumerate(target_features):
    print(f"Target: {target}")
    print(f"MSE: {mse_values[i]:.2f}")
    print(f"R-squared: {r2_values[i]:.2f}")

# Determine if water is safe or not based on a threshold
threshold = 0.1  # You can adjust the threshold as needed
water_safety = ["Safe" if prediction[0] <= threshold else "Dangerous" for prediction in predicted_targets]

print("Water Safety:")
for i, safety in enumerate(water_safety):
    print(f"Sample {i + 1}: {safety}")





